[package]
name = "backup"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
flate2 = "1.0.33"
ssh2 = "0.9.4"
tar = "0.4.41"
chrono = "0.4.38"
cron = "0.12.1"
tokio = { version = "1.40.0", features = ["time", "rt", "rt-multi-thread", "macros"] }
fs_extra = "1.3.0"
rand = "0.8.5"
