FROM debian:12.7

RUN apt-get update  \
    && apt-get install -y openssh-client libssh-dev curl \
    && curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh \
    && rm -rf /var/lib/apt/lists/* /get-docker.sh
